---
# File: roles/quantum_orchestrator/handlers/main.yml
# Version: FINAL - Using project_src only

- name: Restart Quantum Orchestrator stack
  # Ensures the QO stack defined by the compose file on disk is running/restarted.
  community.docker.docker_compose_v2:
    project_name: qo_stack
    project_src: "{{ qo_deploy_dir }}" # Use project_src consistent with task
    state: present     # Ensure services are running per the file on disk
    # recreate: always # Consider if more forceful restart needed
  become: yes
