---
# Tasks for installing and configuring Docker CE (with GPG Key Workaround)

- name: Ensure prerequisites for Docker repo are installed
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg # Ensure gnupg is installed for the gpg command later if needed
    state: present
    update_cache: yes
  become: true
  tags: [docker, packages]

# Remove conflicting docker.io package if present (best effort)
- name: Ensure conflicting docker.io package is removed
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - podman-docker
      - containerd
      - runc
    state: absent
  ignore_errors: true
  become: true
  tags: [docker, packages]

- name: Ensure Docker apt key directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true
  tags: [docker, repo]

# --- Start: Replaced GPG Key Download Task ---
- name: Add Docker's official GPG key (using curl command)
  ansible.builtin.command:
    # Use curl on the target: fail silently on error (-f), show no progress (-s), follow redirects (-L), output to file (-o)
    cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    creates: /etc/apt/keyrings/docker.asc # Makes task idempotent - only run if file doesn't exist
  become: true
  changed_when: false # Idempotency handled by 'creates'
  tags: [docker, repo]

- name: Ensure Docker GPG key has correct permissions
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.asc # Path where key was saved
    mode: '0644'
    owner: root
    group: root
  become: true
  tags: [docker, repo]
# --- End: Replaced GPG Key Download Task ---

- name: Add Docker's official APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable" # Ensure signed-by matches .asc path
    state: present
    filename: docker # Creates /etc/apt/sources.list.d/docker.list
    update_cache: yes
  become: true
  tags: [docker, repo]

- name: Install Docker CE packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io # Required by docker-ce
      - docker-buildx-plugin
      - docker-compose-plugin # Installs 'docker compose' command
    state: present
  become: true
  tags: [docker, packages]
  # notify: Restart docker # Optional handler if needed

- name: Ensure docker group exists
  ansible.builtin.group:
    name: docker
    state: present
  become: true
  tags: [docker, users]

- name: Add specified users to the docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true # Add to existing groups
  loop: "{{ docker_users_to_group | default([]) }}"
  become: true
  tags: [docker, users]

- name: Ensure Docker service is enabled and running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  become: true
  tags: [docker, service]
